import { createContext, useContext, useState, useCallback, useEffect, type ReactNode } from 'react';
import {
  CognitoIdentityProviderClient,
  InitiateAuthCommand,
} from '@aws-sdk/client-cognito-identity-provider';
import type { AuthSession, DemoUser } from '../types';

// Cognito config — generated by setup/5_configure_frontend.sh into frontend/.env
const COGNITO_REGION = import.meta.env.VITE_COGNITO_REGION ?? 'us-east-1';
const COGNITO_CLIENT_ID = import.meta.env.VITE_COGNITO_CLIENT_ID ?? '';

// Demo user mapping — username → actor_id + password (for quick-select)
const DEMO_USER_MAP: Record<string, { actor_id: string; password: string }> = {
  'bob-policyholder': { actor_id: 'PH-1001', password: 'DemoPass1!' },
  'alice-policyholder': { actor_id: 'PH-1042', password: 'DemoPass2!' },
  'charlie-policyholder': { actor_id: 'PH-1087', password: 'DemoPass3!' },
  'david-policyholder': { actor_id: 'PH-2001', password: 'DemoPass4!' },
  'sarah-policyholder': { actor_id: 'PH-2050', password: 'DemoPass5!' },
  'marcus-policyholder': { actor_id: 'PH-3001', password: 'DemoPass6!' },
  'lisa-policyholder': { actor_id: 'PH-3050', password: 'DemoPass7!' },
  // Adjuster (HITL review console) — not a policyholder, so no actor_id.
  'dana-adjuster': { actor_id: '', password: 'AdjustPass1!' },
  // Admin (memory inspector / debug).
  'amy-admin': { actor_id: '', password: 'AdminPass1!' },
};

/** Decode a JWT payload (no verification — the server verifies). */
function decodeGroups(idToken?: string): string[] {
  if (!idToken) return [];
  try {
    const part = idToken.split('.')[1];
    let b64 = part.replace(/-/g, '+').replace(/_/g, '/');
    b64 += '='.repeat((4 - (b64.length % 4)) % 4); // restore base64 padding
    const json = JSON.parse(decodeURIComponent(escape(atob(b64))));
    return json['cognito:groups'] ?? [];
  } catch {
    return [];
  }
}

const cognitoClient = new CognitoIdentityProviderClient({ region: COGNITO_REGION });

interface AuthContextValue {
  session: AuthSession | null;
  login: (username: string, password?: string) => Promise<void>;
  logout: () => void;
  loading: boolean;
  error: string | null;
}

const SESSION_KEY = 'claims-demo-session';

function loadSession(): AuthSession | null {
  try {
    const raw = sessionStorage.getItem(SESSION_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

const AuthContext = createContext<AuthContextValue | null>(null);

export function AuthProvider({ children }: { children: ReactNode }) {
  const [session, setSession] = useState<AuthSession | null>(loadSession);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (session) {
      sessionStorage.setItem(SESSION_KEY, JSON.stringify(session));
    } else {
      sessionStorage.removeItem(SESSION_KEY);
    }
  }, [session]);

  const login = useCallback(async (username: string, password?: string) => {
    setLoading(true);
    setError(null);

    try {
      // For quick-select users, use the known password
      const demoUser = DEMO_USER_MAP[username];
      const pw = password ?? demoUser?.password;
      if (!pw) {
        throw new Error('Password required for non-demo users');
      }

      // Authenticate against Cognito
      const command = new InitiateAuthCommand({
        AuthFlow: 'USER_PASSWORD_AUTH',
        ClientId: COGNITO_CLIENT_ID,
        AuthParameters: {
          USERNAME: username,
          PASSWORD: pw,
        },
      });

      const response = await cognitoClient.send(command);
      const tokens = response.AuthenticationResult;

      if (!tokens?.AccessToken) {
        throw new Error('Authentication failed — no tokens returned');
      }

      // Determine actor_id
      const actorId = demoUser?.actor_id ?? username;

      const user: DemoUser = { username, actor_id: actorId };

      setSession({
        user,
        accessToken: tokens.AccessToken,
        idToken: tokens.IdToken,
        groups: decodeGroups(tokens.IdToken),
      });
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Login failed';
      setError(message);
    } finally {
      setLoading(false);
    }
  }, []);

  const logout = useCallback(() => setSession(null), []);

  return (
    <AuthContext.Provider value={{ session, login, logout, loading, error }}>
      {children}
    </AuthContext.Provider>
  );
}

export function useAuth() {
  const ctx = useContext(AuthContext);
  if (!ctx) throw new Error('useAuth must be used within AuthProvider');
  return ctx;
}
